language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install pymysql"
script: cd test && make -s
services:
  - mysql
before_script:
  - mysql -uroot -e "grant all on *.* to test@'localhost' identified by 'test' with grant option"
